### ISSUE TITLE
clean_html() causes NotImplementedError

### ISSUE THREAD

**Issue by marianoju** [ype/MLRSS#2]
```
Traceback (most recent call last):
  File "/[...]/opml_cluster_agg.py", line 56, in <module>
    words = nltk.wordpunct_tokenize(nltk.clean_html(e['description']))
  File "/[...]/anaconda3/envs/mlrss/lib/python2.7/site-packages/nltk/util.py", line 356, 
  in clean_html
    raise NotImplementedError ("To remove HTML markup, use BeautifulSoup's get_text() 
    function")
NotImplementedError: To remove HTML markup, use BeautifulSoup's get_text() function

Process finished with exit code 1
```

cf. [clean_html() is a cute function in NLTK that was dropped since BeautifulSoup does a better job](https://stackoverflow.com/a/26019529)

**Comment by ype** [comment]
The above commit adds a function to implement nltk clean_html which was removed in favour of bs4's get_text

Tested in clean virtualenv - can confirm it is now working
